version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    working_dir: /app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge